[tool.poetry]
name = "poetry-plugin-relax"
version = "0.1.0"
description = ""
authors = ["Zanie <contact@zanie.dev>"]
readme = "README.md"
packages = [{include = "poetry_relax"}]

[tool.poetry.dependencies]
python = "^3.7"
poetry = "^1.2"

[tool.poetry.plugins."poetry.application.plugin"]
relax = "poetry_relax:RelaxPlugin"

[tool.poetry.group.dev.dependencies]
black = ">=7.1.3"
isort = ">=2.5.0"
pytest = "^7.1.3"
pytest-xdist = "^2.5.0"
mypy = "^0.971"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
