name: Build

env:
  POETRY_VERSION: "1.2.0"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Poetry
        run: |
          pip install poetry==${{ env.POETRY_VERSION }}

      - name: Install local poetry-relax
        run: |
          poetry self add $(pwd)

      - name: Relax constraints
        run: |
          poetry relax

      - name: Publish package
        env:
          POETRY_PYPI_TOKEN_TEST_PYPI: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          version=$(./bin/version dev)
          poetry version $version
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry publish --build -r test-pypi
          # Each time we generate a dev version it gets a new timestamp so we store the
          # version in a variable for the next step
          echo "POETRY_RELAX_VERSION=$version" >> $GITHUB_ENV

      - name: Test package installation
        run: |
          poetry source add test-pypi https://test.pypi.org/simple/ --secondary
          poetry add --source test-pypi poetry-relax==${{ env.POETRY_RELAX_VERSION }}
          installed=$(python -c "import pkg_resources; print(pkg_resources.get_distribution('poetry_relax').version)")
          test $installed = ${{ env.POETRY_RELAX_VERSION }}
