name: Release

env:
  POETRY_VERSION: "1.2.0"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+rc[0-9]+"
      - "[0-9]+.[0-9]+[ab][0-9]+"

jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Poetry
        run: |
          pip install poetry==${{ env.POETRY_VERSION }}

      - name: Relax constraints
        if: ${{ matrix.relax }}
        run: |
          poetry self add $(pwd)
          poetry relax

      - name: Build package
        run: |
          poetry build

      - name: Publish package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry version ${{ github.ref }}
          poetry publish
